Vagrant.configure("2") do |config|
 
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.provider "hyperv" do |v|
    v.cpus = 2
    v.vmname = "vagrant_docker_minikube"
    v.memory = 4096
    v.maxmemory = 4096
  end

  config.vm.synced_folder "C:/_DEV/_GIT", "/home/vagrant/git"

end
