apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mikrostoritev
  name: mikrostoritev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mikrostoritev
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mikrostoritev
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://spring-db:3306/meas
          image: iideveloper21/measurements
          name: mikrostoritev
          ports:
            - containerPort: 8280
          resources: {}
      restartPolicy: Always
status: {}
