Vagrant.configure("2") do |config|
 
  config.vm.box = "gusztavvargadr/docker-linux"
  
  #config.vm.provider "virtualbox" do |v|
  #  v.memory = 4096
  #end

  #config.vm.network "forwarded_port", guest: 80, host: 80
  #config.vm.network "forwarded_port", guest: 88, host: 88
  #config.vm.network "forwarded_port", guest: 3000, host: 3000
  #config.vm.network "forwarded_port", guest: 8000, host: 8000
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  #config.vm.network "forwarded_port", guest: 8180, host: 8180
  #config.vm.network "forwarded_port", guest: 8280, host: 8280
  #config.vm.network "forwarded_port", guest: 8380, host: 8380
  #config.vm.network "forwarded_port", guest: 8480, host: 8480
  #config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.provider "hyperv" do |v|
    v.cpus = 2
    v.vmname = "vagrant_docker"
    v.memory = 4096
    v.maxmemory = 4096
  end
  
  config.vm.synced_folder "C:/_DEV/_GIT", "/home/vagrant/git"
  
end
